[package]
name = "strom-ppm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strom-image-common = {path = "../strom-image-common"}
strom-color = { path = "../../basic/strom-color" }